safe: true
title: 'Brad Dunbar'
author: 'Brad Dunbar'
description: 'Programming & Peanut Butter'
url: 'https://braddunbar.net'
permalink: '/:year/:month/:day/:title'
sass:
  style: compressed
plugins:
  - jekyll-feed:
